spring:
  application:
    name: ITEMS-SERVICE  # Fixed typo in name

  datasource:
    url: jdbc:postgresql://localhost:5432/FeignClient_DB  
    username: postgres  
    password: Reddy@2000  
    driver-class-name: org.postgresql.Driver  

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Alternative way to define dialect
    hibernate:
      ddl-auto: update  
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true  
    ip-address: 127.0.0.1    
    hostname: localhost      
    instance-id: ${spring.application.name}:${server.port}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs  # ✅ Default OpenAPI docs path
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
