spring:
  application:
    name: USER-SERVICE  
  datasource:
    url: jdbc:postgresql://localhost:5432/FeignClient_DB  
    username: postgres  
    password: Reddy@2000  
    driver-class-name: org.postgresql.Driver  
  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true  # ✅ Register using IP instead of hostname
    ip-address: 127.0.0.1    # ✅ Explicitly set IP to localhost
    hostname: localhost      # ✅ Set hostname to localhost
    instance-id: ${spring.application.name}:${server.port}  # ✅ Prevents caching old registrations

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs  # Default path for OpenAPI docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
