server:
  port: 8761  # Eureka Server runs on port 8761

spring:
  application:
    name: eureka-server
  main:
    allow-bean-definition-overriding: true
    web-application-type: servlet
  datasource:
    url: ""  # Disable database configuration
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  # Eureka server doesn't register itself
    fetch-registry: false        # Doesn't fetch other services
