server:
  port: 8761  # Eureka Server runs on port 8761

spring:
  application:
    name: eureka-server
  main:
    allow-bean-definition-overriding: true
    web-application-type: servlet
  datasource:
    url: ""  # No database needed for Eureka
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  client:
    register-with-eureka: false  # ❌ Eureka Server itself does not register
    fetch-registry: false  # ❌ Eureka Server does not fetch registry
    service-url:
      defaultZone: http://localhost:8761/eureka/  # ✅ Ensure Eureka URL is localhost
  server:
    enable-self-preservation: false  # ❌ Disable self-preservation for testing (optional)
  instance:
    hostname: localhost  # ✅ Set Eureka Server hostname to localhost
